name: Build Docker Containers

run-name: ${{ github.actor }} is building Docker containers

on:
  workflow_call

jobs:
  containers_build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: djtesting
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: test-key-not-good
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Create .env file
        run: |
          touch .env
          echo DB_CONNECTION=postgresql >> .env
          echo DB_HOST=${{ env.POSTGRES_HOST }} >> .env
          echo DB_PORT=${{ env.POSTGRES_PORT }} >> .env
          echo DB_NAME=${{ env.POSTGRES_DB }} >> .env
          echo DB_USERNAME=${{ env.POSTGRES_USER }} >> .env
          echo DB_PASSWORD=${{ env.POSTGRES_PASSWORD }} >> .env
          cat .env

      - name: Build containers
        run: |
          docker compose -f docker-compose-prod.yml build
